title: Dr1
description: Dr1 is a project at the [Florida Tech Dynamic Systems, Controls, and Mechatronics Lab.](https://research.fit.edu/dynamic-systems-and-controls-lab/). The main goal of the project is to benchmark NASA's SVGS technology against other commercially available technologies by precisely landing a drone
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
